.PHNOY: install

install: 
	rm -rf */	
	mkdir spam_legacy
	R-3.3.1 CMD INSTALL spam_1.4-0.tar.gz -l spam_legacy/
	R-3.3.1 CMD INSTALL dotCall64_0.9-04.tar.gz -l .
	R-3.3.1 CMD INSTALL spam_2.0-05.tar.gz -l .
	R-3.3.1 CMD INSTALL spam64_2.0-05.tar.gz -l .


